name: tricare_patient_application
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:




  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.5
  flutter_facebook_auth: ^6.2.0


  map_launcher: ^2.4.0

  #google_fonts
  google_fonts: any

  #dropdown_button
  dropdown_button2: ^1.2.3

  #bloc:
  flutter_bloc: ^8.1.2


  #bottom navigation bar
  animated_bottom_navigation_bar: ^1.2.0

  #SVG icon
  flutter_svg: ^1.1.6

  #slider
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.1.0

  #animations
  flutter_animate: ^4.3.0

  #icons
  awesome_icons: ^1.1.0

  #url_launcher
  url_launcher: ^6.1.6


  shared_preferences: ^2.0.15
  pin_code_fields: ^8.0.1


  dio: ^5.4.1
  connectivity_plus: ^5.0.2

  awesome_snackbar_content: ^0.0.8

  awesome_dialog: ^3.0.2



  animate_do: ^2.1.0

  image_picker: ^0.8.6

  image_cropper: any

  number_paginator: ^0.0.2

  loading_animation_widget: ^1.2.0+4

  google_nav_bar: ^5.0.6

  shimmer: ^3.0.0

  otp_text_field: ^1.1.3

  loader_overlay: ^2.1.0

  flutter_spinkit: ^5.2.0

  cached_network_image: ^3.3.0

  permission_handler: ^11.0.1
  animated_rating_stars: ^1.0.1
  rate: ^0.0.2

  loading_btn: ^1.0.3


  searchfield: ^0.9.0
  easy_stepper: ^0.8.4



  flutter_widget_from_html_core: ^0.14.11


  rename: ^3.0.1

  badges: ^3.1.2


  #PDF
  syncfusion_flutter_pdfviewer: any


  flutter_launcher_icons: ^0.13.1

  infinite_scroll_pagination: ^4.0.0


  #localization
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1




  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

dev_dependencies:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/bg_logo.png"


  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
